//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtividadeDataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registo
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public Nullable<System.DateTime> Data_Hora_Login { get; set; }
        public System.DateTime Data_Hora_Logoff { get; set; }
    
        public virtual User User { get; set; }
    }
}
