//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizador()
        {
            this.Agendamento = new HashSet<Agendamento>();
            this.Agendamento1 = new HashSet<Agendamento>();
            this.Declaracao = new HashSet<Declaracao>();
            this.Pedido_Declaracao = new HashSet<Pedido_Declaracao>();
            this.Pedido_Esclarecimento = new HashSet<Pedido_Esclarecimento>();
            this.Pedido_Esclarecimento1 = new HashSet<Pedido_Esclarecimento>();
            this.Reportar_Problema = new HashSet<Reportar_Problema>();
            this.Reportar_Problema1 = new HashSet<Reportar_Problema>();
            this.Sugestao = new HashSet<Sugestao>();
            this.Utilizador_Perfil = new HashSet<Utilizador_Perfil>();
        }
    
        public int id { get; set; }
        public string cod_postal { get; set; }
        public string nome { get; set; }
        public string cc { get; set; }
        public string n_eleitor { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Declaracao> Declaracao { get; set; }
        public virtual Freguesia Freguesia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Declaracao> Pedido_Declaracao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Esclarecimento> Pedido_Esclarecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Esclarecimento> Pedido_Esclarecimento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportar_Problema> Reportar_Problema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportar_Problema> Reportar_Problema1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sugestao> Sugestao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizador_Perfil> Utilizador_Perfil { get; set; }
    }
}
